In [1]:
import numpy as np
import pandas as pd
import random

import sys
sys.path.insert(1, './../utils/')
from utils_main import *

# Loading in the data

In [2]:
portfolio, profile, transcript  = readFiles(dropUnnecessaryCol = True)

# Dealing with missing values in the `profile` dataset (Optionnal)

In [4]:
profile = missingValuesProfileIncome(profile, how = 'impute')

In [5]:
profile = missingValuesProfileGender(profile, how = 'impute')

In [6]:
profile = missingValuesProfileAge(profile, how = 'impute')

# Pre-processing

In [7]:
profile_prep = preprocessing(portfolio, profile, transcript)

# One-hot encoding

In [8]:
portfolio, profile, transcript = oneHotEncoder(portfolio, profile, transcript, dropUnnecessaryCol = True)

# Final dataframe ready for clustering

In [9]:
profile_prep

,id_membership,prep_tot_aver_spend_bogo,prep_tot_aver_spend_discount,prep_recency,prep_T,prep_nb_of_offer_view,prep_nb_of_offer_rec,prep_nb_of_transactions,prep_nb_of_offer_comp,prep_tot_spend,prep_tot_aver_spend,gender,age,became_member_on,income
0,0009655768c64bdeb2e877511632db8f,8.570,12.190,19.0,20.0,4.0,5.0,8.0,3.0,127.60,15.9500,M,33.0,2017-04-21,72000.0
1,0011e0d4e6b944f998e987f904e8c1e5,22.050,16.990,21.0,24.0,5.0,5.0,5.0,3.0,79.46,15.8920,O,40.0,2018-01-09,57000.0
2,0020c2b971eb4e9188eac86d93036a77,17.240,17.435,28.0,28.0,3.0,5.0,8.0,3.0,196.86,24.6075,F,59.0,2016-03-04,90000.0
3,0020ccbbb6d84e358d3414a3ff76cffd,12.425,11.650,26.0,28.0,4.0,4.0,12.0,3.0,154.05,12.8375,F,24.0,2016-11-11,60000.0
4,004b041fbfe44859945daa2c7f79ee64,27.920,19.930,29.0,29.0,2.0,3.0,6.0,2.0,138.36,23.0600,F,55.0,2018-05-08,74000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16995,afd41b230f924f9ca8f5ed6249616114,0.000,0.000,-1.0,-1.0,0.0,2.0,0.0,0.0,0.00,0.0000,M,51.0,2017-01-03,78000.0
16996,ce1579c557c14f7785869dc80638bc0f,0.000,0.000,-1.0,-1.0,0.0,3.0,0.0,0.0,0.00,0.0000,F,79.0,2016-05-24,72000.0
16997,df9fc9a86ca84ef5aedde8925d5838ba,0.000,0.000,-1.0,-1.0,0.0,2.0,0.0,0.0,0.00,0.0000,M,54.0,2017-09-05,65000.0
16998,e63e42480aae4ede9f07cac49c8c3f78,0.000,0.000,-1.0,-1.0,0.0,2.0,0.0,0.0,0.00,0.0000,F,70.0,2016-11-02,79000.0
16999,f67a6524092d48a788a415c453bd2e00,0.000,0.000,-1.0,-1.0,0.0,3.0,0.0,0.0,0.00,0.0000,F,50.0,2016-06-09,106000.0