In [1]:
import numpy as np
import pandas as pd
import random
import imp

import sys
sys.path.insert(1, './../utils/')
from utils_main import *

# Loading in the data

In [2]:
portfolio, profile, transcript  = readFiles(dropUnnecessaryCol = True)

# Dealing with missing values in the `profile` dataset (Optionnal)

In [3]:
profile = missingValuesProfileIncome(profile, how = 'impute')

In [4]:
profile = missingValuesProfileGender(profile, how = 'impute')

In [5]:
profile = missingValuesProfileAge(profile, how = 'impute')

# Pre-processing

In [6]:
profile = preprocessing(portfolio, profile, transcript)

# One-hot encoding

In [7]:
portfolio, profile, transcript = oneHotEncoder(portfolio, profile, transcript, dropUnnecessaryCol = True)

In [8]:
profile

,id_membership,prep_tot_aver_spend_exc_offers,prep_tot_aver_reward,prep_tot_aver_spend_bogo,prep_tot_aver_spend_discount,prep_recency,prep_T,prep_nb_of_offer_view,prep_nb_of_offer_rec,prep_nb_of_transactions,...,year_joined_2015,year_joined_2016,year_joined_2017,year_joined_2018,age_cat_high,age_cat_low,age_cat_medium,income_cat_high,income_cat_low,income_cat_medium
0,0009655768c64bdeb2e877511632db8f,18.930000,3.000000,8.570,12.190,19.0,20.0,4.0,5.0,8.0,...,0,0,1,0,0,0,1,1,0,0
1,00116118485d4dfda04fdbaba9a87b5c,1.363333,0.000000,0.000,0.000,8.0,18.0,2.0,2.0,3.0,...,0,0,0,1,1,0,0,0,0,1
2,0011e0d4e6b944f998e987f904e8c1e5,15.160000,4.333333,22.050,16.990,21.0,24.0,5.0,5.0,5.0,...,0,0,0,1,0,0,1,0,0,1
3,0020c2b971eb4e9188eac86d93036a77,26.998333,4.666667,17.240,17.435,28.0,28.0,3.0,5.0,8.0,...,0,1,0,0,1,0,0,1,0,0
4,0020ccbbb6d84e358d3414a3ff76cffd,13.061111,4.333333,12.425,11.650,26.0,28.0,4.0,4.0,12.0,...,0,1,0,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16995,afd41b230f924f9ca8f5ed6249616114,0.000000,0.000000,0.000,0.000,-1.0,-1.0,0.0,2.0,0.0,...,0,0,1,0,1,0,0,1,0,0
16996,ce1579c557c14f7785869dc80638bc0f,0.000000,0.000000,0.000,0.000,-1.0,-1.0,0.0,3.0,0.0,...,0,1,0,0,1,0,0,1,0,0
16997,df9fc9a86ca84ef5aedde8925d5838ba,0.000000,0.000000,0.000,0.000,-1.0,-1.0,0.0,2.0,0.0,...,0,0,1,0,1,0,0,0,0,1
16998,e63e42480aae4ede9f07cac49c8c3f78,0.000000,0.000000,0.000,0.000,-1.0,-1.0,0.0,2.0,0.0,...,0,1,0,0,1,0,0,1,0,0
16999,f67a6524092d48a788a415c453bd2e00,0.000000,0.000000,0.000,0.000,-1.0,-1.0,0.0,3.0,0.0,...,0,1,0,0,1,0,0,1,0,0

# Final dataframe ready for clustering

In [8]:
profile

,id_membership,prep_tot_aver_spend_exc_offers,prep_tot_aver_reward,prep_tot_aver_spend_bogo,prep_tot_aver_spend_discount,prep_recency,prep_T,prep_nb_of_offer_view,prep_nb_of_offer_rec,prep_nb_of_transactions,...,age_cat,gender_F,gender_M,gender_O,year_joined_2013,year_joined_2014,year_joined_2015,year_joined_2016,year_joined_2017,year_joined_2018
0,0009655768c64bdeb2e877511632db8f,18.930000,3.000000,8.570,12.190,19.0,20.0,4.0,5.0,8.0,...,high,0,1,0,0,0,0,0,1,0
1,00116118485d4dfda04fdbaba9a87b5c,1.363333,0.000000,0.000,0.000,8.0,18.0,2.0,2.0,3.0,...,high,0,1,0,0,0,0,0,0,1
2,0011e0d4e6b944f998e987f904e8c1e5,15.160000,4.333333,22.050,16.990,21.0,24.0,5.0,5.0,5.0,...,high,0,0,1,0,0,0,0,0,1
3,0020c2b971eb4e9188eac86d93036a77,26.998333,4.666667,17.240,17.435,28.0,28.0,3.0,5.0,8.0,...,high,1,0,0,0,0,0,1,0,0
4,0020ccbbb6d84e358d3414a3ff76cffd,13.061111,4.333333,12.425,11.650,26.0,28.0,4.0,4.0,12.0,...,high,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16995,afd41b230f924f9ca8f5ed6249616114,0.000000,0.000000,0.000,0.000,-1.0,-1.0,0.0,2.0,0.0,...,high,0,1,0,0,0,0,0,1,0
16996,ce1579c557c14f7785869dc80638bc0f,0.000000,0.000000,0.000,0.000,-1.0,-1.0,0.0,3.0,0.0,...,high,1,0,0,0,0,0,1,0,0
16997,df9fc9a86ca84ef5aedde8925d5838ba,0.000000,0.000000,0.000,0.000,-1.0,-1.0,0.0,2.0,0.0,...,high,0,1,0,0,0,0,0,1,0
16998,e63e42480aae4ede9f07cac49c8c3f78,0.000000,0.000000,0.000,0.000,-1.0,-1.0,0.0,2.0,0.0,...,high,1,0,0,0,0,0,1,0,0
16999,f67a6524092d48a788a415c453bd2e00,0.000000,0.000000,0.000,0.000,-1.0,-1.0,0.0,3.0,0.0,...,high,1,0,0,0,0,0,1,0,0

# Preprocessing pipeline

In [ ]:
portfolio_, profile_, transcript_ = prepPipeline(dropUnnecessaryCol = False, impute = True)

In [ ]:
profile_

In [ ]:
print(profile_.isnull().sum())